/// Arabic strings (default language, RTL).
const Map<String, String> stringsAr = {
  'appTitle': 'لعبة السياق',
  'tagline': 'اكتشف الكلمة السرية من خلال المعنى',
  'stats': 'الإحصائيات',
  'home': 'الرئيسية',
  'play': 'العب',
  'category': 'التصنيف',
  'difficulty': 'الصعوبة',
  'diffEasy': 'سهل',
  'diffMedium': 'متوسط',
  'diffHard': 'صعب',
  'newGame': 'ابدأ لعبة جديدة',
  'resumeGame': 'متابعة اللعبة',
  'prevAttempts': 'المحاولات السابقة',
  'bestScore': 'أفضل نتيجة',
  'attempts': 'محاولات:',
  'best': 'أفضل:',
  'inputHint': 'أدخل كلمتك هنا...',
  'bestGuess': 'أقرب تخمين',
  'historyTitle': 'السجل',
  'hint': 'تلميح',
  'hintPrefix': 'تلميح',
  'noMoreHints': 'لا مزيد من التلميحات',
  'unknownWord': 'هذه الكلمة غير موجودة في القاموس',
  'didYouMean': 'هل تقصد:',
  'duplicateGuess': 'خمّنت هذه الكلمة من قبل',
  'solvedTitle': 'أحسنت! لقد وجدت الكلمة',
  'secretWordIs': 'الكلمة السرية هي',
  'attemptsLabel': 'المحاولات',
  'rankLabel': 'المركز',
  'hintsLabel': 'التلميحات',
  'closestGuesses': 'أقرب الكلمات التي خمنتها',
  'shareResult': 'مشاركة النتيجة',
  'playAgain': 'لعبة جديدة',
  'rankNo': 'رقم',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'sound': 'الأصوات',
  'haptics': 'الاهتزاز',
  'devServer': 'رابط الخادم (للمطوّرين)',
  'devServerHint': 'اتركه فارغاً لاستخدام الرابط الافتراضي',
  'gamesPlayed': 'ألعاب',
  'gamesSolved': 'حلول',
  'loading': 'جارٍ التحميل...',
  'connecting': 'جارٍ الاتصال بالخادم...',
  'retry': 'إعادة المحاولة',
  'errNetwork': 'تعذّر الاتصال بالخادم. تحقق من اتصالك بالإنترنت.',
  'errTimeout': 'انتهت مهلة الاتصال. حاول مرة أخرى.',
  'errServer': 'حدث خطأ في الخادم. حاول لاحقاً.',
  'errUnknown': 'حدث خطأ غير متوقع.',
  'errGameMissing': 'انتهت هذه اللعبة أو لم تعد متاحة. ابدأ لعبة جديدة.',
  'errNoSuggestions': 'لا توجد اقتراحات',
  'heatBlazing': 'ساخن جداً',
  'heatWarm': 'دافئ',
  'heatCold': 'بارد',
  'heatFreezing': 'متجمد',
  'shareSolvedIn': 'حلّيت الكلمة في {n} محاولات',
  'shareBestRank': 'أفضل ترتيب: #{r}',
  'shareHints': 'التلميحات: {h}/{max}',
  'outOfVocab': 'خارج القاموس',
  'giveUp': 'استسلام',
  'totalWords': 'كلمة',
};
