/// English strings (LTR).
const Map<String, String> stringsEn = {
  'appTitle': 'Siyaq',
  'tagline': 'Discover the secret word through meaning',
  'stats': 'Stats',
  'home': 'Home',
  'play': 'Play',
  'category': 'Category',
  'difficulty': 'Difficulty',
  'diffEasy': 'Easy',
  'diffMedium': 'Medium',
  'diffHard': 'Hard',
  'newGame': 'Start New Game',
  'resumeGame': 'Resume Game',
  'prevAttempts': 'Total Attempts',
  'bestScore': 'Best Score',
  'attempts': 'Guesses:',
  'best': 'Best:',
  'inputHint': 'Enter your word...',
  'bestGuess': 'Closest Guess',
  'historyTitle': 'History',
  'hint': 'Hint',
  'hintPrefix': 'Hint',
  'noMoreHints': 'No more hints',
  'unknownWord': 'This word is not in the dictionary',
  'didYouMean': 'Did you mean:',
  'duplicateGuess': 'You already guessed this word',
  'solvedTitle': 'Well done! You found the word',
  'secretWordIs': 'The secret word is',
  'attemptsLabel': 'Attempts',
  'rankLabel': 'Rank',
  'hintsLabel': 'Hints',
  'closestGuesses': 'Your closest guesses',
  'shareResult': 'Share Result',
  'playAgain': 'New Game',
  'rankNo': 'No.',
  'settings': 'Settings',
  'language': 'Language',
  'sound': 'Sound',
  'haptics': 'Haptics',
  'devServer': 'Server URL (developer)',
  'devServerHint': 'Leave empty to use the default URL',
  'gamesPlayed': 'Games',
  'gamesSolved': 'Solved',
  'loading': 'Loading...',
  'connecting': 'Connecting to server...',
  'retry': 'Retry',
  'offlineTitle': 'The server is currently offline',
  'offlineSubtitle': 'The temporary tunnel link may be down',
  'changeServer': 'Change Server URL',
  'errNetwork': 'Could not reach the server. Check your connection.',
  'errTimeout': 'The request timed out. Try again.',
  'errServer': 'Server error. Try again later.',
  'errUnknown': 'Something went wrong.',
  'errGameMissing': 'This game has expired. Start a new one.',
  'errNoSuggestions': 'No suggestions',
  'heatBlazing': 'Blazing',
  'heatWarm': 'Warm',
  'heatCold': 'Cold',
  'heatFreezing': 'Freezing',
  'shareSolvedIn': 'Solved the word in {n} guesses',
  'shareBestRank': 'Best rank: #{r}',
  'shareHints': 'Hints: {h}/{max}',
  'outOfVocab': 'out of vocabulary',
  'giveUp': 'Give up',
  'totalWords': 'words',
  // ---- V2 ----
  'modeSolo': 'Solo Game',
  'modeWeekly': 'Weekly Challenge',
  'modeMultiplayer': 'Play With Friends',
  'modeSoloDesc': 'Play on your own and find the secret word',
  'modeWeeklyDesc': "Take on everyone with this week's word",
  'modeMultiplayerDesc': 'Create a room or join your friends',
  'comingSoon': 'Coming soon',
  'unavailableNow': 'Currently unavailable',
  'langArabic': 'Arabic',
  'langEnglish': 'English',
  'chooseGameLang': 'Choose game language',
  'gameLangLocked': 'Game language is locked for this session',
  'abandonGameTitle': 'Abandon current game?',
  'abandonGameBody':
      'Your current session will be lost if you start in a different language.',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'displayName': 'Display name',
  'setNameTitle': 'Choose a display name',
  'setNameBody': 'This name appears on the leaderboard and in rooms.',
  'setNameHint': 'Your name (optional)',
  'save': 'Save',
  'skip': 'Skip',
  'editName': 'Edit name',
  'privacyNote':
      'No account, no device identifier — an anonymous identity on this device only.',
  'yourCode': 'Your code',
  'weekly': 'Weekly Challenge',
  'weeklyThisWeek': 'Week',
  'timeRemaining': 'Time remaining',
  'participation': 'Your participation',
  'notStarted': 'Not started',
  'inProgress': 'In progress',
  'completed': 'Completed',
  'startWeekly': 'Start challenge',
  'resumeWeekly': 'Resume challenge',
  'leaderboard': 'Leaderboard',
  'yourPlacement': 'Your placement',
  'weeklyResultTitle': 'Weekly Challenge Result',
  'elapsed': 'Time',
  'placement': 'Placement',
  'returnHome': 'Return home',
  'createRoom': 'Create Room',
  'joinRoom': 'Join Room',
  'resumeRoom': 'Resume room',
  'joinCode': 'Join code',
  'enterJoinCode': 'Enter join code',
  'copy': 'Copy',
  'copied': 'Copied',
  'players': 'Players',
  'host': 'Host',
  'startRoom': 'Start game',
  'leaveRoom': 'Leave room',
  'maxPlayers': 'Max players',
  'you': 'You',
  'waitingForHost': 'Waiting for the host to start',
  'connected': 'Connected',
  'connecting2': 'Connecting',
  'reconnecting': 'Reconnecting...',
  'winnerTitle': 'Winner',
  'rematch': 'Rematch',
  'newRoom': 'New room',
  'sharedDuplicateBy': 'First guessed by: {name}',
  'systemHint': 'System hint',
  'hintStandard': 'Standard',
  'hintAdaptive': 'Adaptive',
  'hintStandardExplain': 'A fixed hint that nudges you toward the meaning.',
  'hintAdaptiveExplain': 'Hints adapt to the best word you reached yourself.',
  'hintMode': 'Hint mode',
  'canonicalDuplicate': 'You already tried this word or one of its forms: {w}',
  'v2ErrUnsupported': 'Server version unsupported. Please update the app.',
  'v2ErrProfileBlocked': 'This profile is temporarily blocked.',
  'v2ErrWeeklyUnavailable': 'The weekly challenge is unavailable right now.',
  'v2ErrWeeklyExpired': 'This weekly challenge has ended.',
  'v2ErrWeeklyCompleted': 'You already completed this challenge.',
  'v2ErrRoomInvalid': 'Invalid or expired room code.',
  'v2ErrRoomFull': 'The room is full.',
  'v2ErrRoomStarted': 'The game in this room has already started.',
  'v2ErrRoomSolved': 'This room has already been solved.',
  'v2ErrRoomExpired': 'This room has expired.',
  'v2ErrDuplicateRoomGuess': 'That word was already guessed in the room.',
  'v2ErrAdaptiveUnavailable': 'Adaptive hint is unavailable right now.',
  'v2ErrRateLimited': 'Too many attempts, please wait a moment.',
  'v2Reconnecting': 'Connection lost, retrying...',
  'appearance': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'notifications': 'Notifications',
  'notificationsHint': 'Get game, room and match updates.',
  'notificationsBlocked': 'Turned off in system settings.',
  'notificationsDenied': 'Allow notifications in system settings to enable them.',
  'openSettings': 'Open settings',
  'copyToken': 'Copy device token',
  'tokenCopied': 'Device token copied',
  'tokenUnavailable': 'Token not ready yet — try again in a moment.',
  'account': 'Account',
  'guestMode': 'Guest',
  'signInWithGoogle': 'Sign in with Google',
  'signInBenefit': 'Save your progress and play Ranked & Social Rooms.',
  'signOut': 'Sign out',
  'linkedGoogle': 'Linked with Google',
  'playerId': 'Player ID',
  'idCopied': 'Player ID copied',
  'signedInNote':
      'Signed in with Google — your progress syncs across your devices.',
  'guestIdentityNote':
      'Anonymous identity on this device only — no account, no device id.',
  'nameHint': 'Your name',
  'welcomeTitle': 'Welcome to Siyaq',
  'welcomeBody':
      'Choose how your name appears to other players. You can change it anytime.',
  'signInFailed': 'Sign-in failed. Please try again.',
  'signInConfigError': 'Sign-in isn\'t available on this device right now.',
  'v2ErrSignInRequired': 'Please sign in to continue.',
  'v2ErrAccountDisabled': 'This account is disabled. Contact support.',
  'v2ErrDisplayName': 'That name isn\'t allowed. Try another.',
  'v2ErrLanguageLocked': 'This game is locked to another language.',
  'v2ErrRoomNotActive': 'Waiting for the host to start.',
  'v2ErrInsufficientCoins': 'Not enough coins. Earn more to play.',
  'v2ErrWalletBlocked': 'Your wallet is frozen. Contact support.',
  'v2ErrTier': 'This tier is unavailable. Pick another.',
  'v2ErrMatchmakingActive': 'You\'re already searching for a match.',
  'v2ErrMatchActive': 'You already have an active match.',
  'v2ErrNotYourTurn': 'It\'s not your turn yet.',
  'v2ErrTurnExpired': 'Your turn expired.',
  'v2ErrOpponentDropped': 'Opponent disconnected — waiting…',
  'v2ErrForfeit': 'The match was forfeited.',
  'v2ErrMatchCancelled': 'Match cancelled and refunded.',
  'v2ErrPlayerUnavailable': 'This player is busy or offline.',
  'v2ErrInvitesDisabled': 'This player isn\'t accepting invites.',
  'v2ErrInviteSelf': 'You can\'t invite yourself.',
  'v2ErrInvitationExpired': 'That invitation expired.',
  'v2ErrRequestsClosed': 'This room isn\'t accepting requests.',
  'v2ErrNotHost': 'Only the host can do that.',
  'v2ErrActiveRoomExists': 'Finish or leave your current room first.',
  'v2ErrStateConflict': 'That changed — refreshing…',
  'v2ErrNotInVocabulary': 'That word isn\'t in the dictionary.',
  'v2MockPreview': 'Preview V2 (mock data)',
  'v2MockPreviewHint':
      'Shows Weekly & Multiplayer on mock data before the backend is available.',
};
