/// English strings (LTR).
const Map<String, String> stringsEn = {
  'appTitle': 'Siyaq',
  'tagline': 'Discover the secret word through meaning',
  'stats': 'Stats',
  'home': 'Home',
  'play': 'Play',
  'category': 'Category',
  'difficulty': 'Difficulty',
  'diffEasy': 'Easy',
  'diffMedium': 'Medium',
  'diffHard': 'Hard',
  'newGame': 'Start New Game',
  'resumeGame': 'Resume Game',
  'prevAttempts': 'Total Attempts',
  'bestScore': 'Best Score',
  'attempts': 'Guesses:',
  'best': 'Best:',
  'inputHint': 'Enter your word...',
  'bestGuess': 'Closest Guess',
  'historyTitle': 'History',
  'hint': 'Hint',
  'hintPrefix': 'Hint',
  'noMoreHints': 'No more hints',
  'unknownWord': 'This word is not in the dictionary',
  'didYouMean': 'Did you mean:',
  'duplicateGuess': 'You already guessed this word',
  'solvedTitle': 'Well done! You found the word',
  'secretWordIs': 'The secret word is',
  'attemptsLabel': 'Attempts',
  'rankLabel': 'Rank',
  'hintsLabel': 'Hints',
  'closestGuesses': 'Your closest guesses',
  'shareResult': 'Share Result',
  'playAgain': 'New Game',
  'rankNo': 'No.',
  'settings': 'Settings',
  'language': 'Language',
  'sound': 'Sound',
  'haptics': 'Haptics',
  'devServer': 'Server URL (developer)',
  'devServerHint': 'Leave empty to use the default URL',
  'gamesPlayed': 'Games',
  'gamesSolved': 'Solved',
  'loading': 'Loading...',
  'connecting': 'Connecting to server...',
  'invitations': 'invitations',
  'retry': 'Retry',
  'offlineTitle': 'The server is currently offline',
  'offlineSubtitle': 'The temporary tunnel link may be down',
  'changeServer': 'Change Server URL',
  'errNetwork': 'Could not reach the server. Check your connection.',
  'errTimeout': 'The request timed out. Try again.',
  'errServer': 'Server error. Try again later.',
  'errRejectedWord': "That word couldn't be used — try another",
  'errUnknown': 'Something went wrong.',
  'errGameMissing': 'This game has expired. Start a new one.',
  'errNoSuggestions': 'No suggestions',
  'heatBlazing': 'Blazing',
  'heatWarm': 'Warm',
  'heatCold': 'Cold',
  'heatFreezing': 'Freezing',
  'shareSolvedIn': 'Solved the word in {n} guesses',
  'shareBestRank': 'Best rank: #{r}',
  'shareHints': 'Hints: {h}/{max}',
  'outOfVocab': 'out of vocabulary',
  'giveUp': 'Give up',
  'totalWords': 'words',
  // ---- V2 ----
  'modeSolo': 'Solo Game',
  'modeWeekly': 'Weekly Challenge',
  'modeMultiplayer': 'Play with Friends',
  'modeSoloDesc': 'Play alone and improve your skills',
  'modeWeeklyDesc': 'One word, all week, glory for the best',
  'modeMultiplayerDesc': 'Play the same word with friends in real time',
  'comingSoon': 'Coming soon',
  'unavailableNow': 'Currently unavailable',
  'langArabic': 'Arabic',
  'langEnglish': 'English',
  'chooseGameLang': 'Choose game language',
  'langNoCategories': 'Not available in this language yet',
  'langNoCategoriesBody': 'Pick another game language above to play now.',
  'gameLangLocked': 'Game language is locked for this session',
  'abandonGameTitle': 'Abandon current game?',
  'abandonGameBody':
      'Your current session will be lost if you start in a different language.',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'displayName': 'Display name',
  'setNameTitle': 'Choose a display name',
  'setNameBody': 'This name appears on the leaderboard and in rooms.',
  'setNameHint': 'Your name (optional)',
  'save': 'Save',
  'skip': 'Skip',
  'editName': 'Edit name',
  'privacyNote':
      'No account, no device identifier — an anonymous identity on this device only.',
  'yourCode': 'Your code',
  'weekly': 'Weekly Challenge',
  'weeklyThisWeek': 'Week',
  'timeRemaining': 'Time remaining',
  'participation': 'Your participation',
  'notStarted': 'Not started',
  'inProgress': 'In progress',
  'completed': 'Completed',
  'startWeekly': 'Start challenge',
  'resumeWeekly': 'Resume challenge',
  'leaderboard': 'Leaderboard',
  'yourPlacement': 'Your placement',
  'weeklyResultTitle': 'Weekly Challenge Result',
  'elapsed': 'Time',
  'placement': 'Placement',
  'returnHome': 'Return home',
  'createRoom': 'Create Game',
  'joinRoom': 'Join Game',
  'resumeRoom': 'Resume room',
  'joinCode': 'Join code',
  'enterJoinCode': 'Enter join code',
  'copy': 'Copy',
  'stepOf': 'Step {n} of {total}',
  'share': 'Share',
  'waitingForPlayers': 'Waiting for players to join',
  'copied': 'Copied',
  'players': 'Online Players',
  'host': 'Host',
  'startRoom': 'Start game',
  'leaveRoom': 'Leave room',
  'maxPlayers': 'Max players',
  'you': 'You',
  'waitingForHost': 'Waiting for the host to start',
  'connected': 'Connected',
  'connecting2': 'Connecting',
  'reconnecting': 'Reconnecting...',
  'winnerTitle': 'Winner',
  'rematch': 'Rematch',
  'newRoom': 'New room',
  'sharedDuplicateBy': 'First guessed by: {name}',
  'hintStandard': 'Standard',
  'hintAdaptive': 'Adaptive',
  'hintStandardExplain': 'A fixed hint that nudges you toward the meaning.',
  'hintAdaptiveExplain': 'Hints adapt to the best word you reached yourself.',
  'hintMode': 'Hint mode',
  'canonicalDuplicate': 'You already tried this word or one of its forms: {w}',
  'v2ErrUnsupported': 'Server version unsupported. Please update the app.',
  'v2ErrProfileBlocked': 'This profile is temporarily blocked.',
  'v2ErrWeeklyUnavailable': 'The weekly challenge is unavailable right now.',
  'v2ErrWeeklyExpired': 'This weekly challenge has ended.',
  'v2ErrWeeklyCompleted': 'You already completed this challenge.',
  'v2ErrRoomInvalid': 'Invalid or expired room code.',
  'v2ErrRoomFull': 'The room is full.',
  'v2ErrRoomStarted': 'The game in this room has already started.',
  'v2ErrRoomSolved': 'This room has already been solved.',
  'v2ErrRoomExpired': 'This room has expired.',
  'v2ErrDuplicateRoomGuess': 'That word was already guessed in the room.',
  'v2ErrAdaptiveUnavailable': 'Adaptive hint is unavailable right now.',
  'v2ErrRateLimited': 'Too many attempts, please wait a moment.',
  'v2Reconnecting': 'Connection lost, retrying...',
  'appearance': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'notifications': 'Notifications',
  'notificationsHint': 'Get game, room and match updates.',
  'notificationsReady':
      'Registered and ready for game, room and match updates.',
  'notificationsWaiting': 'Permission granted. Waiting for the device token.',
  'notificationsRegistering': 'Registering this device for notifications...',
  'notificationsRecoverableError':
      'Registration did not finish. The app will retry shortly.',
  'notificationsBlocked': 'Turned off in system settings.',
  'notificationsDenied':
      'Allow notifications in system settings to enable them.',
  'openSettings': 'Open settings',
  'copyToken': 'Copy device token',
  'tokenCopied': 'Device token copied',
  'tokenUnavailable': 'Token not ready yet — try again in a moment.',
  'account': 'Account',
  'guestMode': 'Guest',
  'signInWithGoogle': 'Sign in with Google',
  'signInWithApple': 'Sign in with Apple',
  'signInBenefit': 'Save your progress and play Ranked & Social Rooms.',
  'signOut': 'Sign out',
  'linkedGoogle': 'Linked with Google',
  'linkedApple': 'Linked with Apple',
  'playerId': 'Player ID',
  'copyHint': 'Double tap to copy',
  'idCopied': 'Player ID copied',
  'signedInNote':
      'Signed in with Google — your progress syncs across your devices.',
  'guestIdentityNote':
      'Anonymous identity on this device only — no account, no device id.',
  'nameHint': 'Your name',
  'welcomeTitle': 'Welcome to Siyaq',
  'welcomeBody':
      'Choose how your name appears to other players. You can change it anytime.',
  'signInFailed': 'Sign-in failed. Please try again.',
  'signInConfigError': 'Sign-in isn\'t available on this device right now.',
  'v2ErrSignInRequired': 'Please sign in to continue.',
  'v2ErrReauth': 'Please sign in again to continue.',
  'v2ErrProviderDisabled': 'This sign-in method is currently unavailable.',
  'v2ErrInstallation':
      'Something went wrong with this device. Please try again.',
  'v2ErrAccountDisabled': 'This account is disabled. Contact support.',
  'v2ErrAccountSuspended': 'Your account is suspended. Contact support.',
  'v2ErrAccountBanned': 'Your account has been banned.',
  'v2ErrAccountVerification': 'Please verify your account to continue.',
  'v2ErrAccountDeletionPending': 'Your account is scheduled for deletion.',
  'v2ErrAccountDeleted': 'This account has been deleted.',
  'v2ErrDisplayName': 'That name isn\'t allowed. Try another.',
  'v2ErrLanguageLocked': 'This game is locked to another language.',
  'v2ErrRoomNotActive': 'Waiting for the host to start.',
  'v2ErrInsufficientCoins': 'Not enough coins. Earn more to play.',
  'v2ErrWalletBlocked': 'Your wallet is frozen. Contact support.',
  'v2ErrTier': 'This tier is unavailable. Pick another.',
  'v2ErrMatchmakingActive': 'You\'re already searching for a match.',
  'v2ErrMatchActive': 'You already have an active match.',
  'v2ErrNotYourTurn': 'It\'s not your turn yet.',
  'v2ErrTurnExpired': 'Your turn expired.',
  'v2ErrOpponentDropped': 'Opponent disconnected — waiting…',
  'v2ErrForfeit': 'The match was forfeited.',
  'v2ErrMatchCancelled': 'Match cancelled and refunded.',
  'v2ErrPlayerUnavailable': 'This player is busy or offline.',
  'v2ErrInvitesDisabled': 'This player isn\'t accepting invites.',
  'v2ErrInviteSelf': 'You can\'t invite yourself.',
  'v2ErrInvitationExpired': 'That invitation expired.',
  'v2ErrRequestsClosed': 'This room isn\'t accepting requests.',
  'v2ErrNotHost': 'Only the host can do that.',
  'v2ErrActiveRoomExists': 'Finish or leave your current room first.',
  'v2ErrStateConflict': 'That changed — refreshing…',
  'v2ErrNotInVocabulary': 'That word isn\'t in the dictionary.',
  // ---- UX polish: consumer naming, descriptions & states ----
  'createGameDesc': 'Start a new game and invite friends',
  'joinGameDesc': "Enter an invite code to join a friend's game",
  'competitive': 'Competitive Match',
  'competitiveDesc': 'Challenge another player and win points',
  'onlinePlayersDesc': "See who's online and invite them",
  'signIn': 'Sign In',
  'refresh': 'Refresh',
  'invitePlayers': 'Invite players',
  'invite': 'Invite',
  'invited': 'Invited',
  'invites': 'Invitations',
  'onlineNow': 'Online now',
  'accept': 'Accept',
  'dismiss': 'Dismiss',
  'gameInvitation': 'Game invitation',
  'invitedBy': 'from {name}',
  'pullToRefresh': 'Pull down to refresh',
  'uDay': 'd',
  'uHour': 'h',
  'uMin': 'm',
  // guest / empty / loading / error states
  'guestPlayersTitle': 'Sign in required',
  'guestPlayersBody':
      'Sign in to play with others, send invites, and save your progress.',
  'noPlayersTitle': 'No players online right now',
  'noPlayersBody': 'Try again later or invite your friends.',
  'loadingPlayers': 'Loading players...',
  'creatingGame': 'Creating game...',
  'joiningGame': 'Joining...',
  'searchingPlayers': 'Finding a player...',
  'errLoadPlayers': "Couldn't load players",
  'errRoomUnavailable': 'This game is no longer available.',
  'errInviteFailed': "Couldn't send the invitation.",
  'errAcceptFailed': "Couldn't accept the invitation.",
  'errOpenGame': "Couldn't open the game.",
  // presence
  'presAvailable': 'Available',
  'presAway': 'Away',
  'presInGame': 'In a game',
  'presInLobby': 'In a game',
  'presSearching': 'Searching',
  'presInMatch': 'In a match',
  'presReconnecting': 'Reconnecting',
  'presOffline': 'Offline',
  // ---- UX polish P2: confirmations ----
  'stay': 'Stay',
  'leave': 'Leave',
  'back': 'Back',
  'confirmLeaveTitle': 'Leave the game?',
  'confirmLeaveBody': 'You may lose your current turn.',
  'confirmForfeitTitle': 'Leave the match?',
  'confirmForfeitBody': 'Leaving the match counts as a loss. Are you sure?',
  'confirmLogoutTitle': 'Sign out?',
  'confirmLogoutBody': 'You can come back later with the same account.',
  // ---- UX polish P2: join game ----
  'enterGameCode': 'Enter the game code',
  'join': 'Join',
  'searchingGame': 'Finding the game...',
  'gameNotFoundTitle': 'Game not found',
  'gameNotFoundBody': 'Check the code and try again.',
  'gameFull': 'The game is full',
  'gameEnded': 'This game has ended.',
  // ---- UX polish P2: create game wizard ----
  'chooseLanguage': 'Choose Language',
  'chooseCategory': 'Choose Category',
  'chooseMode': 'Choose Game Mode',
  'choosePlayers': 'Players Count',
  'next': 'Next',
  'step': 'Step',
  'gameModeLabel': 'Mode',
  'languageLabel': 'Language',
  'playersLabel': 'Players',
  'modeNormal': 'Normal Mode',
  'modeNormalDesc': 'Free hints for everyone — friendly play',
  'modeCompetitive': 'Competitive Mode',
  'modeCompetitiveDesc': 'Limited hints — first to solve wins',
  'playersCount': '{n} Players',
  'summaryTitle': 'Ready',
  'loadingGeneric': 'Loading...',
  'emptyGeneric': 'Nothing here yet',
  'somethingWrong': 'Something went wrong',
  'send': 'Send',
  'guessAWord': 'Guess a word',
  'waitYourTurn': 'Wait your turn',
  // ---- UX polish P3: localization audit ----
  'guessesLabel': 'Guesses',
  'bandSolved': 'Answer',
  'bandBlazing': 'Blazing',
  'bandHot': 'Hot',
  'bandWarm': 'Warm',
  'bandLukewarm': 'Lukewarm',
  'bandCold': 'Cold',
  'progFirst': 'First guess — here we go!',
  'progBlazing': 'You are in the blazing zone!',
  'progCloser': 'Closer than ever!',
  'progWarmer': 'You are getting closer…',
  'progKeepTrying': 'Keep going — try another angle',
  'guessesCount': '{n} guesses',
  'distanceLabel': 'Distance',
  'noGuessesYet': 'Start with any word',
  'noGuessesBody':
      'Every guess is scored by how close its meaning is to the secret word.',
  'guessHistory': 'Your guesses',
  'hintsLeftN': '{n} left',
  'hintsNone': 'No hints left',
  'noHintsYet': 'No hints revealed yet',
  'showHints': 'Show hints',
  'hideHints': 'Hide hints',
  'submitGuess': 'Submit guess',
  'gameLanguage': 'Game language',
  'hintsRevealedN': '{n} revealed',
  'systemHint': 'System hint',
  'hintAuthor': 'Hint',
  'opponentLabel': 'Opponent',
  'sharedHistory': 'Shared guesses',
  'noRankYet': '—',
  'viewResult': 'View result',
  'bestRankLabel': 'Best rank',
  'weeklyExpired': 'Challenge ended',
  'settingOn': 'On',
  'settingOff': 'Off',
  "errLoadInvites": "Couldn't load invitations — pull to refresh",
  'coins': 'Coins',
  'noTranslations': 'No suggestions for this word',
  'releaseInfoSectionTitle': "Game data",
  'wordDataVersionLabel': "Word data version",
  'datasetVersionLabel': "Dataset version",
  'languagePackLabel': "Language pack",
  'releaseIdLabel': "Release ID",
  'newGamesReleaseLabel': "New games release",
  'currentGameReleaseLabel': "Current game release",
  'currentGamePinnedLabel': "Pinned",
  'releaseChangedForNewGamesMessage':
      "Your current game remains on its original word-data version. New games use the newer version.",
  'legacyUnknownReleaseLabel': "Unknown legacy release",
  'releaseStatusActiveLabel': "Active",
  'sourceCommitLabel': "Source commit",
  'releaseComponentsLabel': "Composed from",
  'sessionReleaseLabel': "This game's release",
  'releaseUpdatedLabel': "Policy updated",
  'nasijBandDistant': "Distant",
  'nasijBandAdjacent': "Adjacent",
  'nasijBandRelated': "Related",
  'nasijBandNear': "Near",
  'nasijBandTouching': "Touching",
  'nasijBandSolved': "Solved",
  'gameplayModeClassic': "Classic",
  'gameplayModeOrbit': "Orbit",
  'translationTitle': "Arabic → English",
  'translationLoading': "Finding translations…",
  'translationError': "Couldn't load translations",
  'translationRetry': "Try again",
  'translationMore': "More translations",
  'translationAnnounce': "{n} translation suggestions available",
  'closest': 'Closest',
  'latest': 'Latest',
  'hints': 'Hints',
  'enterYourWord': 'Type your word...',
  'solved': 'Solved!',
  'viewMyRank': 'View my rank',
  'weeklyLoadError': "Couldn't load the challenge",
  'startGame': 'Start game',
  'winner': 'Winner',
  'roomsWon': 'Rooms',
  'bestLabel': 'Best',
  'uDayFull': 'days',
  'uHourFull': 'hours',
  'uMinFull': 'min',
  'theWordWas': 'The word was',
  'unknownPlayer': 'Unknown player',
  // ranked screen
  'chooseStake': 'Choose your stake',
  'noTiers': 'No stakes available right now',
  'searchFailed': "Couldn't start the search. Try again.",
  'rating': 'Rating',
  'record': 'Record',
  'entryPrize': 'Entry {e} · Prize {p}',
  'winnerTakesStake': 'Winner takes the stake',
  'insufficientBalance': 'Not enough balance',
  'search': 'Search',
  'searchingOpponent': 'Finding an opponent…',
  'winShort': 'W',
  'lossShort': 'L',
  // ranked match
  'vs': 'vs',
  'ready': 'Ready',
  'getReady': 'Get ready for the match',
  'theWordLabel': 'The word',
  'timeline': 'Timeline',
  'imReady': "I'm ready",
  'waitingOpponent': 'Waiting for opponent…',
  'youWon': 'You won!',
  'matchEnded': 'Match over',
  'ratingPts': 'pts',
  'yourTurn': 'Your turn',
  'opponentTurn': "Opponent's turn",
  'secShort': 's',
  'revealHint': 'Reveal a hint',
  'availableToInvite': 'Available to invite',
  'shareRoomCode': 'Game code: {code}',
};
