/// English strings (LTR).
const Map<String, String> stringsEn = {
  'appTitle': 'Siyaq',
  'tagline': 'Discover the secret word through meaning',
  'stats': 'Stats',
  'home': 'Home',
  'play': 'Play',
  'category': 'Category',
  'difficulty': 'Difficulty',
  'diffEasy': 'Easy',
  'diffMedium': 'Medium',
  'diffHard': 'Hard',
  'newGame': 'Start New Game',
  'resumeGame': 'Resume Game',
  'prevAttempts': 'Total Attempts',
  'bestScore': 'Best Score',
  'attempts': 'Guesses:',
  'best': 'Best:',
  'inputHint': 'Enter your word...',
  'bestGuess': 'Closest Guess',
  'historyTitle': 'History',
  'hint': 'Hint',
  'hintPrefix': 'Hint',
  'noMoreHints': 'No more hints',
  'unknownWord': 'This word is not in the dictionary',
  'didYouMean': 'Did you mean:',
  'duplicateGuess': 'You already guessed this word',
  'solvedTitle': 'Well done! You found the word',
  'secretWordIs': 'The secret word is',
  'attemptsLabel': 'Attempts',
  'rankLabel': 'Rank',
  'hintsLabel': 'Hints',
  'closestGuesses': 'Your closest guesses',
  'shareResult': 'Share Result',
  'playAgain': 'New Game',
  'rankNo': 'No.',
  'settings': 'Settings',
  'language': 'Language',
  'sound': 'Sound',
  'haptics': 'Haptics',
  'devServer': 'Server URL (developer)',
  'devServerHint': 'Leave empty to use the default URL',
  'gamesPlayed': 'Games',
  'gamesSolved': 'Solved',
  'loading': 'Loading...',
  'connecting': 'Connecting to server...',
  'retry': 'Retry',
  'errNetwork': 'Could not reach the server. Check your connection.',
  'errTimeout': 'The request timed out. Try again.',
  'errServer': 'Server error. Try again later.',
  'errUnknown': 'Something went wrong.',
  'errGameMissing': 'This game has expired. Start a new one.',
  'errNoSuggestions': 'No suggestions',
  'heatBlazing': 'Blazing',
  'heatWarm': 'Warm',
  'heatCold': 'Cold',
  'heatFreezing': 'Freezing',
  'shareSolvedIn': 'Solved the word in {n} guesses',
  'shareBestRank': 'Best rank: #{r}',
  'shareHints': 'Hints: {h}/{max}',
  'outOfVocab': 'out of vocabulary',
  'giveUp': 'Give up',
  'totalWords': 'words',
};
