/// Arabic strings (default language, RTL).
const Map<String, String> stringsAr = {
  'appTitle': 'لعبة السياق',
  'tagline': 'اكتشف الكلمة السرية من خلال المعنى',
  'stats': 'الإحصائيات',
  'home': 'الرئيسية',
  'play': 'العب',
  'category': 'التصنيف',
  'difficulty': 'الصعوبة',
  'diffEasy': 'سهل',
  'diffMedium': 'متوسط',
  'diffHard': 'صعب',
  'newGame': 'ابدأ لعبة جديدة',
  'resumeGame': 'متابعة اللعبة',
  'prevAttempts': 'المحاولات السابقة',
  'bestScore': 'أفضل نتيجة',
  'attempts': 'محاولات:',
  'best': 'أفضل:',
  'inputHint': 'أدخل كلمتك هنا...',
  'bestGuess': 'أقرب تخمين',
  'historyTitle': 'السجل',
  'hint': 'تلميح',
  'hintPrefix': 'تلميح',
  'noMoreHints': 'لا مزيد من التلميحات',
  'unknownWord': 'هذه الكلمة غير موجودة في القاموس',
  'didYouMean': 'هل تقصد:',
  'duplicateGuess': 'خمّنت هذه الكلمة من قبل',
  'solvedTitle': 'أحسنت! لقد وجدت الكلمة',
  'secretWordIs': 'الكلمة السرية هي',
  'attemptsLabel': 'المحاولات',
  'rankLabel': 'المركز',
  'hintsLabel': 'التلميحات',
  'closestGuesses': 'أقرب الكلمات التي خمنتها',
  'shareResult': 'مشاركة النتيجة',
  'playAgain': 'لعبة جديدة',
  'rankNo': 'رقم',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'sound': 'الأصوات',
  'haptics': 'الاهتزاز',
  'devServer': 'رابط الخادم (للمطوّرين)',
  'devServerHint': 'اتركه فارغاً لاستخدام الرابط الافتراضي',
  'gamesPlayed': 'ألعاب',
  'gamesSolved': 'حلول',
  'loading': 'جارٍ التحميل...',
  'connecting': 'جارٍ الاتصال بالخادم...',
  'retry': 'إعادة المحاولة',
  'offlineTitle': 'الخادم غير متصل حالياً',
  'offlineSubtitle': 'قد يكون رابط النفق المؤقت متوقفاً',
  'changeServer': 'تغيير رابط الخادم',
  'errNetwork': 'تعذّر الاتصال بالخادم. تحقق من اتصالك بالإنترنت.',
  'errTimeout': 'انتهت مهلة الاتصال. حاول مرة أخرى.',
  'errServer': 'حدث خطأ في الخادم. حاول لاحقاً.',
  'errUnknown': 'حدث خطأ غير متوقع.',
  'errGameMissing': 'انتهت هذه اللعبة أو لم تعد متاحة. ابدأ لعبة جديدة.',
  'errNoSuggestions': 'لا توجد اقتراحات',
  'heatBlazing': 'ساخن جداً',
  'heatWarm': 'دافئ',
  'heatCold': 'بارد',
  'heatFreezing': 'متجمد',
  'shareSolvedIn': 'حلّيت الكلمة في {n} محاولات',
  'shareBestRank': 'أفضل ترتيب: #{r}',
  'shareHints': 'التلميحات: {h}/{max}',
  'outOfVocab': 'خارج القاموس',
  'giveUp': 'استسلام',
  'totalWords': 'كلمة',
  // ---- V2 ----
  'modeSolo': 'لعبة فردية',
  'modeWeekly': 'الكلمة الأسبوعية',
  'modeMultiplayer': 'اللعب مع الأصدقاء',
  'modeSoloDesc': 'العب بمفردك واكتشف الكلمة السرية',
  'modeWeeklyDesc': 'تحدَّ الجميع على كلمة الأسبوع',
  'modeMultiplayerDesc': 'أنشئ غرفة أو انضم لأصدقائك',
  'comingSoon': 'قريباً',
  'unavailableNow': 'غير متاح حالياً',
  'langArabic': 'العربية',
  'langEnglish': 'الإنجليزية',
  'chooseGameLang': 'اختر لغة اللعب',
  'gameLangLocked': 'لغة اللعب مثبّتة لهذه الجلسة',
  'abandonGameTitle': 'ترك اللعبة الحالية؟',
  'abandonGameBody': 'ستُفقد جلستك الحالية إذا بدأت بلغة مختلفة.',
  'confirm': 'تأكيد',
  'cancel': 'إلغاء',
  'displayName': 'الاسم الظاهر',
  'setNameTitle': 'اختر اسماً للظهور',
  'setNameBody': 'سيظهر هذا الاسم في لوحة الصدارة والغرف.',
  'setNameHint': 'اسمك (اختياري)',
  'save': 'حفظ',
  'skip': 'تخطٍّ',
  'editName': 'تعديل الاسم',
  'privacyNote':
      'لا نستخدم أي حساب أو معرّف جهاز — هوية مجهولة على هذا الجهاز فقط.',
  'yourCode': 'رمزك',
  'weekly': 'الكلمة الأسبوعية',
  'weeklyThisWeek': 'أسبوع',
  'timeRemaining': 'الوقت المتبقّي',
  'participation': 'مشاركتك',
  'notStarted': 'لم تبدأ',
  'inProgress': 'قيد اللعب',
  'completed': 'مكتملة',
  'startWeekly': 'ابدأ التحدي',
  'resumeWeekly': 'متابعة التحدي',
  'leaderboard': 'لوحة الصدارة',
  'yourPlacement': 'ترتيبك',
  'weeklyResultTitle': 'نتيجة التحدي الأسبوعي',
  'elapsed': 'الوقت',
  'placement': 'الترتيب',
  'returnHome': 'العودة للرئيسية',
  'createRoom': 'إنشاء غرفة',
  'joinRoom': 'انضمام لغرفة',
  'resumeRoom': 'متابعة الغرفة',
  'joinCode': 'رمز الغرفة',
  'enterJoinCode': 'أدخل رمز الغرفة',
  'copy': 'نسخ',
  'copied': 'تم النسخ',
  'players': 'اللاعبون',
  'host': 'المضيف',
  'startRoom': 'ابدأ اللعبة',
  'leaveRoom': 'مغادرة الغرفة',
  'maxPlayers': 'أقصى عدد لاعبين',
  'you': 'أنت',
  'waitingForHost': 'بانتظار المضيف لبدء اللعبة',
  'connected': 'متصل',
  'connecting2': 'جارٍ الاتصال',
  'reconnecting': 'إعادة الاتصال...',
  'winnerTitle': 'الفائز',
  'rematch': 'لعبة أخرى',
  'newRoom': 'غرفة جديدة',
  'sharedDuplicateBy': 'خمّنها أولاً: {name}',
  'systemHint': 'تلميح النظام',
  'hintStandard': 'عادي',
  'hintAdaptive': 'تكيّفي',
  'hintStandardExplain': 'تلميح ثابت يقودك نحو المعنى.',
  'hintAdaptiveExplain': 'يتحسّن التلميح حسب أفضل كلمة وصلت إليها بنفسك.',
  'hintMode': 'نمط التلميح',
  'canonicalDuplicate': 'جربت هذه الكلمة أو أحد تصريفاتها سابقاً: {w}',
  'v2ErrUnsupported': 'إصدار الخادم غير مدعوم. حدّث التطبيق.',
  'v2ErrProfileBlocked': 'تم حظر هذا الملف مؤقتاً.',
  'v2ErrWeeklyUnavailable': 'التحدي الأسبوعي غير متاح حالياً.',
  'v2ErrWeeklyExpired': 'انتهى هذا التحدي الأسبوعي.',
  'v2ErrWeeklyCompleted': 'لقد أكملت هذا التحدي.',
  'v2ErrRoomInvalid': 'رمز الغرفة غير صحيح أو منتهٍ.',
  'v2ErrRoomFull': 'الغرفة ممتلئة.',
  'v2ErrRoomStarted': 'بدأت اللعبة في هذه الغرفة.',
  'v2ErrRoomSolved': 'انتهت هذه الغرفة بالفوز.',
  'v2ErrRoomExpired': 'انتهت صلاحية هذه الغرفة.',
  'v2ErrDuplicateRoomGuess': 'خُمّنت هذه الكلمة في الغرفة سابقاً.',
  'v2ErrAdaptiveUnavailable': 'التلميح التكيّفي غير متاح الآن.',
  'v2ErrRateLimited': 'محاولات كثيرة، انتظر قليلاً.',
  'v2Reconnecting': 'انقطع الاتصال، جارٍ إعادة المحاولة...',
  'appearance': 'المظهر',
  'themeSystem': 'النظام',
  'themeLight': 'فاتح',
  'themeDark': 'داكن',
  'notifications': 'الإشعارات',
  'notificationsHint': 'استلم تحديثات اللعبة والغرف والمباريات.',
  'notificationsReady':
      'تم تسجيل هذا الجهاز وأصبح جاهزاً لتحديثات اللعبة والغرف والمباريات.',
  'notificationsWaiting': 'تم منح الإذن. ننتظر رمز الجهاز من النظام.',
  'notificationsRegistering': 'جارٍ تسجيل هذا الجهاز للإشعارات...',
  'notificationsRecoverableError':
      'لم يكتمل التسجيل. سيحاول التطبيق مرة أخرى بعد قليل.',
  'notificationsBlocked': 'معطّلة من إعدادات النظام.',
  'notificationsDenied': 'اسمح بالإشعارات من إعدادات النظام لتفعيلها.',
  'openSettings': 'فتح الإعدادات',
  'copyToken': 'نسخ رمز الجهاز',
  'tokenCopied': 'تم نسخ رمز الجهاز',
  'tokenUnavailable': 'الرمز غير جاهز بعد — حاول بعد لحظات.',
  'account': 'الحساب',
  'guestMode': 'ضيف',
  'signInWithGoogle': 'تسجيل الدخول عبر Google',
  'signInWithApple': 'تسجيل الدخول عبر Apple',
  'signInBenefit': 'احفظ تقدمك والعب المصنّفة والغرف الاجتماعية.',
  'signOut': 'تسجيل الخروج',
  'linkedGoogle': 'مرتبط بحساب Google',
  'playerId': 'معرّف اللاعب',
  'idCopied': 'تم نسخ معرّف اللاعب',
  'signedInNote': 'مسجّل الدخول عبر Google — يتزامن تقدمك عبر أجهزتك.',
  'guestIdentityNote':
      'هوية مجهولة على هذا الجهاز فقط — لا حساب ولا معرّف جهاز.',
  'nameHint': 'اسمك',
  'welcomeTitle': 'مرحباً بك في سياق',
  'welcomeBody': 'اختر كيف يظهر اسمك للاعبين الآخرين. يمكنك تغييره في أي وقت.',
  'signInFailed': 'تعذّر تسجيل الدخول. حاول مرة أخرى.',
  'signInConfigError': 'تسجيل الدخول غير متاح على هذا الجهاز حالياً.',
  'v2ErrSignInRequired': 'الرجاء تسجيل الدخول للمتابعة.',
  'v2ErrReauth': 'يرجى تسجيل الدخول مجدداً للمتابعة.',
  'v2ErrProviderDisabled': 'طريقة تسجيل الدخول هذه غير متاحة حالياً.',
  'v2ErrInstallation': 'حدث خطأ متعلّق بهذا الجهاز. حاول مرة أخرى.',
  'v2ErrAccountDisabled': 'هذا الحساب معطّل. تواصل مع الدعم.',
  'v2ErrAccountSuspended': 'حسابك موقوف. تواصل مع الدعم.',
  'v2ErrAccountBanned': 'تم حظر حسابك.',
  'v2ErrAccountVerification': 'يرجى توثيق حسابك للمتابعة.',
  'v2ErrAccountDeletionPending': 'حسابك مجدوَل للحذف.',
  'v2ErrAccountDeleted': 'تم حذف هذا الحساب.',
  'v2ErrDisplayName': 'هذا الاسم غير مسموح. جرّب اسماً آخر.',
  'v2ErrLanguageLocked': 'هذه اللعبة مقفلة على لغة أخرى.',
  'v2ErrRoomNotActive': 'بانتظار المضيف لبدء اللعبة.',
  'v2ErrInsufficientCoins': 'لا توجد عملات كافية. اكسب المزيد للّعب.',
  'v2ErrWalletBlocked': 'محفظتك مجمّدة. تواصل مع الدعم.',
  'v2ErrTier': 'هذه الفئة غير متاحة. اختر غيرها.',
  'v2ErrMatchmakingActive': 'أنت تبحث عن مباراة بالفعل.',
  'v2ErrMatchActive': 'لديك مباراة نشطة بالفعل.',
  'v2ErrNotYourTurn': 'ليس دورك بعد.',
  'v2ErrTurnExpired': 'انتهى وقت دورك.',
  'v2ErrOpponentDropped': 'انقطع اتصال الخصم — بالانتظار…',
  'v2ErrForfeit': 'تم التنازل عن المباراة.',
  'v2ErrMatchCancelled': 'أُلغيت المباراة وأُعيدت العملات.',
  'v2ErrPlayerUnavailable': 'هذا اللاعب مشغول أو غير متصل.',
  'v2ErrInvitesDisabled': 'هذا اللاعب لا يقبل الدعوات.',
  'v2ErrInviteSelf': 'لا يمكنك دعوة نفسك.',
  'v2ErrInvitationExpired': 'انتهت صلاحية الدعوة.',
  'v2ErrRequestsClosed': 'هذه الغرفة لا تقبل الطلبات.',
  'v2ErrNotHost': 'المضيف فقط يمكنه فعل ذلك.',
  'v2ErrActiveRoomExists': 'أنهِ غرفتك الحالية أو غادرها أولاً.',
  'v2ErrStateConflict': 'تغيّر ذلك — جارٍ التحديث…',
  'v2ErrNotInVocabulary': 'هذه الكلمة ليست في القاموس.',
};
