/// Arabic strings (default language, RTL).
const Map<String, String> stringsAr = {
  'appTitle': 'لعبة السياق',
  'tagline': 'اكتشف الكلمة السرية من خلال المعنى',
  'stats': 'الإحصائيات',
  'home': 'الرئيسية',
  'play': 'العب',
  'category': 'التصنيف',
  'difficulty': 'الصعوبة',
  'diffEasy': 'سهل',
  'diffMedium': 'متوسط',
  'diffHard': 'صعب',
  'newGame': 'ابدأ لعبة جديدة',
  'resumeGame': 'متابعة اللعبة',
  'prevAttempts': 'المحاولات السابقة',
  'bestScore': 'أفضل نتيجة',
  'attempts': 'محاولات:',
  'best': 'أفضل:',
  'inputHint': 'أدخل كلمتك هنا...',
  'bestGuess': 'أقرب تخمين',
  'historyTitle': 'السجل',
  'hint': 'تلميح',
  'hintPrefix': 'تلميح',
  'noMoreHints': 'لا مزيد من التلميحات',
  'unknownWord': 'هذه الكلمة غير موجودة في القاموس',
  'didYouMean': 'هل تقصد:',
  'duplicateGuess': 'خمّنت هذه الكلمة من قبل',
  'solvedTitle': 'أحسنت! لقد وجدت الكلمة',
  'secretWordIs': 'الكلمة السرية هي',
  'attemptsLabel': 'المحاولات',
  'rankLabel': 'المركز',
  'hintsLabel': 'التلميحات',
  'closestGuesses': 'أقرب الكلمات التي خمنتها',
  'shareResult': 'مشاركة النتيجة',
  'playAgain': 'لعبة جديدة',
  'rankNo': 'رقم',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'sound': 'الأصوات',
  'haptics': 'الاهتزاز',
  'devServer': 'رابط الخادم (للمطوّرين)',
  'devServerHint': 'اتركه فارغاً لاستخدام الرابط الافتراضي',
  'gamesPlayed': 'ألعاب',
  'gamesSolved': 'حلول',
  'loading': 'جارٍ التحميل...',
  'connecting': 'جارٍ الاتصال بالخادم...',
  'invitations': 'دعوات',
  'retry': 'إعادة المحاولة',
  'offlineTitle': 'الخادم غير متصل حالياً',
  'offlineSubtitle': 'قد يكون رابط النفق المؤقت متوقفاً',
  'changeServer': 'تغيير رابط الخادم',
  'errNetwork': 'تعذّر الاتصال بالخادم. تحقق من اتصالك بالإنترنت.',
  'errTimeout': 'انتهت مهلة الاتصال. حاول مرة أخرى.',
  'errServer': 'حدث خطأ في الخادم. حاول لاحقاً.',
  'errRejectedWord': "تعذّر قبول هذه الكلمة، جرّب كلمة أخرى",
  'errUnknown': 'حدث خطأ غير متوقع.',
  'errGameMissing': 'انتهت هذه اللعبة أو لم تعد متاحة. ابدأ لعبة جديدة.',
  'errNoSuggestions': 'لا توجد اقتراحات',
  'heatBlazing': 'ساخن جداً',
  'heatWarm': 'دافئ',
  'heatCold': 'بارد',
  'heatFreezing': 'متجمد',
  'shareSolvedIn': 'حلّيت الكلمة في {n} محاولات',
  'shareBestRank': 'أفضل ترتيب: #{r}',
  'shareHints': 'التلميحات: {h}/{max}',
  'outOfVocab': 'خارج القاموس',
  'giveUp': 'استسلام',
  'totalWords': 'كلمة',
  // ---- V2 ----
  'modeSolo': 'اللعب الفردي',
  'modeWeekly': 'التحدي الأسبوعي',
  'modeMultiplayer': 'اللعب مع الأصدقاء',
  'modeSoloDesc': 'العب وحدك واكتشف كلمات جديدة',
  'modeWeeklyDesc': 'كلمة واحدة، أسبوع كامل، مجد للأفضل',
  'modeMultiplayerDesc': 'العب نفس الكلمة مع أصدقائك في الوقت الحقيقي',
  'comingSoon': 'قريباً',
  'unavailableNow': 'غير متاح حالياً',
  'langArabic': 'العربية',
  'langEnglish': 'الإنجليزية',
  'chooseGameLang': 'اختر لغة اللعب',
  'langAvailable': 'متاحة',
  'langTempUnavailable': 'غير متاحة مؤقتًا',
  'langCheckingAvailability': 'جارٍ التحقق من التوفر',
  'langUnavailableAr': 'لا توجد حاليًا نسخة كلمات فعالة للغة العربية.',
  'langUnavailableArBody': 'يمكنك اختيار English أو المحاولة لاحقًا.',
  'langUnavailableEn': 'لا توجد حاليًا نسخة كلمات فعالة للغة الإنجليزية.',
  'langUnavailableEnBody': 'يمكنك اختيار العربية أو المحاولة لاحقًا.',
  'langTemporarilyUnavailable': 'هذه اللغة غير متاحة مؤقتًا.',
  'langTemporarilyUnavailableBody': 'اختر لغة لعب أخرى أو حاول لاحقًا.',
  'langLoadingRelease': 'ما زالت هذه اللغة قيد التحميل.',
  'langLoadingReleaseBody': 'يجري تجهيز كلماتها. حاول بعد قليل.',
  'langMaintenance': 'هذه اللغة قيد الصيانة.',
  'langMaintenanceBody': 'اختر لغة لعب أخرى أو حاول لاحقًا.',
  'langRuntimeUnavailable': 'تعذّر تقديم هذه اللغة حاليًا.',
  'langRuntimeUnavailableBody': 'اختر لغة لعب أخرى أو حاول لاحقًا.',
  'langAllUnavailable': 'لا توجد لغة لعب متاحة حاليًا.',
  'langAllUnavailableBody': 'يجري تجهيز الكلمات. يرجى المحاولة بعد قليل.',
  'chooseLanguageAction': 'اختيار {lang}',
  'catNoWords': 'لا توجد كلمات متاحة لهذا التصنيف حاليًا.',
  'catNoWordsBody': 'جرّب تصنيفًا آخر.',
  'catPickAnother': 'اختر تصنيفًا آخر',
  'langSelectorA11y': 'لغة اللعب: {lang}، {state}',
  'playDisabledReason': 'اللعب غير متاح لعدم توفر كلمات للغة {lang}.',
  'gameLangLocked': 'لغة اللعب مثبّتة لهذه الجلسة',
  'abandonGameTitle': 'ترك اللعبة الحالية؟',
  'abandonGameBody': 'ستُفقد جلستك الحالية إذا بدأت بلغة مختلفة.',
  'confirm': 'تأكيد',
  'cancel': 'إلغاء',
  'displayName': 'الاسم الظاهر',
  'setNameTitle': 'اختر اسماً للظهور',
  'setNameBody': 'سيظهر هذا الاسم في لوحة الصدارة والغرف.',
  'setNameHint': 'اسمك (اختياري)',
  'save': 'حفظ',
  'skip': 'تخطٍّ',
  'editName': 'تعديل الاسم',
  'privacyNote':
      'لا نستخدم أي حساب أو معرّف جهاز — هوية مجهولة على هذا الجهاز فقط.',
  'yourCode': 'رمزك',
  'weekly': 'الكلمة الأسبوعية',
  'weeklyThisWeek': 'أسبوع',
  'timeRemaining': 'الوقت المتبقّي',
  'participation': 'مشاركتك',
  'notStarted': 'لم تبدأ',
  'inProgress': 'قيد اللعب',
  'completed': 'مكتملة',
  'startWeekly': 'ابدأ التحدي',
  'resumeWeekly': 'متابعة التحدي',
  'leaderboard': 'لوحة الصدارة',
  'yourPlacement': 'ترتيبك',
  'weeklyResultTitle': 'نتيجة التحدي الأسبوعي',
  'elapsed': 'الوقت',
  'placement': 'الترتيب',
  'returnHome': 'العودة للرئيسية',
  'createRoom': 'إنشاء لعبة',
  'joinRoom': 'الانضمام إلى لعبة',
  'resumeRoom': 'متابعة الغرفة',
  'joinCode': 'رمز الغرفة',
  'enterJoinCode': 'أدخل رمز الغرفة',
  'copy': 'نسخ',
  'stepOf': 'الخطوة {n} من {total}',
  'share': 'مشاركة',
  'waitingForPlayers': 'في انتظار انضمام اللاعبين',
  'copied': 'تم النسخ',
  'players': 'اللاعبون المتصلون',
  'host': 'المضيف',
  'startRoom': 'ابدأ اللعبة',
  'leaveRoom': 'مغادرة الغرفة',
  'maxPlayers': 'أقصى عدد لاعبين',
  'you': 'أنت',
  'waitingForHost': 'بانتظار المضيف لبدء اللعبة',
  'connected': 'متصل',
  'connecting2': 'جارٍ الاتصال',
  'reconnecting': 'إعادة الاتصال...',
  'winnerTitle': 'الفائز',
  'rematch': 'لعبة أخرى',
  'newRoom': 'غرفة جديدة',
  'sharedDuplicateBy': 'خمّنها أولاً: {name}',
  'hintStandard': 'عادي',
  'hintAdaptive': 'تكيّفي',
  'hintStandardExplain': 'تلميح ثابت يقودك نحو المعنى.',
  'hintAdaptiveExplain': 'يتحسّن التلميح حسب أفضل كلمة وصلت إليها بنفسك.',
  'hintMode': 'نمط التلميح',
  'canonicalDuplicate': 'جربت هذه الكلمة أو أحد تصريفاتها سابقاً: {w}',
  'v2ErrUnsupported': 'إصدار الخادم غير مدعوم. حدّث التطبيق.',
  'v2ErrProfileBlocked': 'تم حظر هذا الملف مؤقتاً.',
  'v2ErrWeeklyUnavailable': 'التحدي الأسبوعي غير متاح حالياً.',
  'v2ErrWeeklyExpired': 'انتهى هذا التحدي الأسبوعي.',
  'v2ErrWeeklyCompleted': 'لقد أكملت هذا التحدي.',
  'v2ErrRoomInvalid': 'رمز الغرفة غير صحيح أو منتهٍ.',
  'v2ErrRoomFull': 'الغرفة ممتلئة.',
  'v2ErrRoomStarted': 'بدأت اللعبة في هذه الغرفة.',
  'v2ErrRoomSolved': 'انتهت هذه الغرفة بالفوز.',
  'v2ErrRoomExpired': 'انتهت صلاحية هذه الغرفة.',
  'v2ErrDuplicateRoomGuess': 'خُمّنت هذه الكلمة في الغرفة سابقاً.',
  'v2ErrAdaptiveUnavailable': 'التلميح التكيّفي غير متاح الآن.',
  'v2ErrRateLimited': 'محاولات كثيرة، انتظر قليلاً.',
  'v2Reconnecting': 'انقطع الاتصال، جارٍ إعادة المحاولة...',
  'appearance': 'المظهر',
  'themeSystem': 'النظام',
  'themeLight': 'فاتح',
  'themeDark': 'داكن',
  'notifications': 'الإشعارات',
  'notificationsHint': 'استلم تحديثات اللعبة والغرف والمباريات.',
  'notificationsReady':
      'تم تسجيل هذا الجهاز وأصبح جاهزاً لتحديثات اللعبة والغرف والمباريات.',
  'notificationsWaiting': 'تم منح الإذن. ننتظر رمز الجهاز من النظام.',
  'notificationsRegistering': 'جارٍ تسجيل هذا الجهاز للإشعارات...',
  'notificationsRecoverableError':
      'لم يكتمل التسجيل. سيحاول التطبيق مرة أخرى بعد قليل.',
  'notificationsBlocked': 'معطّلة من إعدادات النظام.',
  'notificationsDenied': 'اسمح بالإشعارات من إعدادات النظام لتفعيلها.',
  'openSettings': 'فتح الإعدادات',
  'copyToken': 'نسخ رمز الجهاز',
  'tokenCopied': 'تم نسخ رمز الجهاز',
  'tokenUnavailable': 'الرمز غير جاهز بعد — حاول بعد لحظات.',
  'account': 'الحساب',
  'guestMode': 'ضيف',
  'signInWithGoogle': 'تسجيل الدخول عبر Google',
  'signInWithApple': 'تسجيل الدخول عبر Apple',
  'signInBenefit': 'احفظ تقدمك والعب المصنّفة والغرف الاجتماعية.',
  'signOut': 'تسجيل الخروج',
  'linkedGoogle': 'مرتبط بحساب Google',
  'linkedApple': 'مرتبط بحساب Apple',
  'playerId': 'معرّف اللاعب',
  'copyHint': 'انقر مرتين للنسخ',
  'idCopied': 'تم نسخ معرّف اللاعب',
  'signedInNote': 'مسجّل الدخول عبر Google — يتزامن تقدمك عبر أجهزتك.',
  'guestIdentityNote':
      'هوية مجهولة على هذا الجهاز فقط — لا حساب ولا معرّف جهاز.',
  'nameHint': 'اسمك',
  'welcomeTitle': 'مرحباً بك في سياق',
  'welcomeBody': 'اختر كيف يظهر اسمك للاعبين الآخرين. يمكنك تغييره في أي وقت.',
  'signInFailed': 'تعذّر تسجيل الدخول. حاول مرة أخرى.',
  'signInConfigError': 'تسجيل الدخول غير متاح على هذا الجهاز حالياً.',
  'v2ErrSignInRequired': 'الرجاء تسجيل الدخول للمتابعة.',
  'v2ErrReauth': 'يرجى تسجيل الدخول مجدداً للمتابعة.',
  'v2ErrProviderDisabled': 'طريقة تسجيل الدخول هذه غير متاحة حالياً.',
  'v2ErrInstallation': 'حدث خطأ متعلّق بهذا الجهاز. حاول مرة أخرى.',
  'v2ErrAccountDisabled': 'هذا الحساب معطّل. تواصل مع الدعم.',
  'v2ErrAccountSuspended': 'حسابك موقوف. تواصل مع الدعم.',
  'v2ErrAccountBanned': 'تم حظر حسابك.',
  'v2ErrAccountVerification': 'يرجى توثيق حسابك للمتابعة.',
  'v2ErrAccountDeletionPending': 'حسابك مجدوَل للحذف.',
  'v2ErrAccountDeleted': 'تم حذف هذا الحساب.',
  'v2ErrDisplayName': 'هذا الاسم غير مسموح. جرّب اسماً آخر.',
  'v2ErrLanguageLocked': 'هذه اللعبة مقفلة على لغة أخرى.',
  'v2ErrRoomNotActive': 'بانتظار المضيف لبدء اللعبة.',
  'v2ErrInsufficientCoins': 'لا توجد عملات كافية. اكسب المزيد للّعب.',
  'v2ErrWalletBlocked': 'محفظتك مجمّدة. تواصل مع الدعم.',
  'v2ErrTier': 'هذه الفئة غير متاحة. اختر غيرها.',
  'v2ErrMatchmakingActive': 'أنت تبحث عن مباراة بالفعل.',
  'v2ErrMatchActive': 'لديك مباراة نشطة بالفعل.',
  'v2ErrNotYourTurn': 'ليس دورك بعد.',
  'v2ErrTurnExpired': 'انتهى وقت دورك.',
  'v2ErrOpponentDropped': 'انقطع اتصال الخصم — بالانتظار…',
  'v2ErrForfeit': 'تم التنازل عن المباراة.',
  'v2ErrMatchCancelled': 'أُلغيت المباراة وأُعيدت العملات.',
  'v2ErrPlayerUnavailable': 'هذا اللاعب مشغول أو غير متصل.',
  'v2ErrInvitesDisabled': 'هذا اللاعب لا يقبل الدعوات.',
  'v2ErrInviteSelf': 'لا يمكنك دعوة نفسك.',
  'v2ErrInvitationExpired': 'انتهت صلاحية الدعوة.',
  'v2ErrRequestsClosed': 'هذه الغرفة لا تقبل الطلبات.',
  'v2ErrNotHost': 'المضيف فقط يمكنه فعل ذلك.',
  'v2ErrActiveRoomExists': 'أنهِ غرفتك الحالية أو غادرها أولاً.',
  'v2ErrStateConflict': 'تغيّر ذلك — جارٍ التحديث…',
  'v2ErrNotInVocabulary': 'هذه الكلمة ليست في القاموس.',
  // ---- UX polish: consumer naming, descriptions & states ----
  'createGameDesc': 'ابدأ لعبة جديدة وادعُ أصدقاءك',
  'joinGameDesc': 'أدخل رمز الدعوة للانضمام إلى لعبة صديق',
  'competitive': 'اللعب التنافسي',
  'competitiveDesc': 'تحدَّ لاعباً آخر واربح النقاط',
  'onlinePlayersDesc': 'شاهد من يلعب الآن وادعُهم',
  'signIn': 'تسجيل الدخول',
  'refresh': 'تحديث',
  'invitePlayers': 'دعوة لاعبين',
  'invite': 'دعوة',
  'invited': 'تمت الدعوة',
  'invites': 'الدعوات',
  'onlineNow': 'المتصلون الآن',
  'accept': 'قبول',
  'dismiss': 'تجاهل',
  'gameInvitation': 'دعوة إلى لعبة',
  'invitedBy': 'من {name}',
  'pullToRefresh': 'اسحب للأسفل للتحديث',
  'uDay': 'ي',
  'uHour': 'س',
  'uMin': 'د',
  // guest / empty / loading / error states
  'guestPlayersTitle': 'تحتاج إلى تسجيل الدخول',
  'guestPlayersBody':
      'سجّل الدخول للعب مع الآخرين، وإرسال الدعوات، وحفظ تقدّمك.',
  'noPlayersTitle': 'لا يوجد لاعبون متصلون الآن',
  'noPlayersBody': 'حاول لاحقاً أو ادعُ أصدقاءك.',
  'loadingPlayers': 'جاري تحميل اللاعبين...',
  'creatingGame': 'جاري إنشاء اللعبة...',
  'joiningGame': 'جاري الانضمام...',
  'searchingPlayers': 'جاري البحث عن لاعب...',
  'errLoadPlayers': 'تعذّر تحميل اللاعبين',
  'errRoomUnavailable': 'هذه اللعبة لم تعد متاحة.',
  'errInviteFailed': 'تعذّر إرسال الدعوة.',
  'errAcceptFailed': 'تعذّر قبول الدعوة.',
  'errOpenGame': 'تعذّر فتح اللعبة.',
  // presence
  'presAvailable': 'متاح',
  'presAway': 'بعيد',
  'presInGame': 'يلعب',
  'presInLobby': 'في لعبة',
  'presSearching': 'يبحث',
  'presInMatch': 'في مباراة',
  'presReconnecting': 'يعيد الاتصال',
  'presOffline': 'غير متصل',
  // ---- UX polish P2: confirmations ----
  'stay': 'البقاء',
  'leave': 'مغادرة',
  'back': 'العودة',
  'confirmLeaveTitle': 'هل تريد مغادرة اللعبة؟',
  'confirmLeaveBody': 'قد تفقد دورك الحالي.',
  'confirmForfeitTitle': 'مغادرة المباراة',
  'confirmForfeitBody': 'مغادرة المباراة ستحتسب خسارة. هل أنت متأكد؟',
  'confirmLogoutTitle': 'هل تريد تسجيل الخروج؟',
  'confirmLogoutBody': 'يمكنك العودة لاحقاً باستخدام نفس الحساب.',
  // ---- UX polish P2: join game ----
  'enterGameCode': 'أدخل رمز اللعبة',
  'join': 'انضمام',
  'searchingGame': 'جاري البحث عن اللعبة...',
  'gameNotFoundTitle': 'لم يتم العثور على اللعبة',
  'gameNotFoundBody': 'تأكد من الرمز وحاول مرة أخرى.',
  'gameFull': 'اللعبة ممتلئة',
  'gameEnded': 'هذه اللعبة انتهت.',
  // ---- UX polish P2: create game wizard ----
  'chooseLanguage': 'اختر اللغة',
  'chooseCategory': 'اختر التصنيف',
  'chooseMode': 'اختر وضع اللعب',
  'choosePlayers': 'عدد اللاعبين',
  'next': 'التالي',
  'step': 'خطوة',
  'gameModeLabel': 'الوضع',
  'languageLabel': 'اللغة',
  'playersLabel': 'اللاعبون',
  'modeNormal': 'الوضع العادي',
  'modeNormalDesc': 'تلميحات مجانية للجميع — لعب ودّي',
  'modeCompetitive': 'الوضع التنافسي',
  'modeCompetitiveDesc': 'تلميحات محدودة — من يصل أولاً يفوز',
  'playersCount': '{n} لاعبين',
  'summaryTitle': 'جاهز للبدء',
  'loadingGeneric': 'جاري التحميل...',
  'emptyGeneric': 'لا يوجد شيء هنا بعد',
  'somethingWrong': 'حدث خطأ ما',
  'send': 'أرسل',
  'guessAWord': 'خمّن كلمة',
  'waitYourTurn': 'انتظر دورك',
  // ---- UX polish P3: localization audit ----
  'guessesLabel': 'التخمينات',
  'bandSolved': 'الإجابة',
  'bandBlazing': 'ملتهب',
  'bandHot': 'حار',
  'bandWarm': 'دافئ',
  'bandLukewarm': 'فاتر',
  'bandCold': 'بارد',
  'progFirst': 'أول تخمين — لنبدأ!',
  'progBlazing': 'دخلت المنطقة الملتهبة!',
  'progCloser': 'أقرب من أي وقت مضى!',
  'progWarmer': 'أنت تقترب…',
  'progKeepTrying': 'استمر — جرّب زاوية أخرى',
  'guessesCount': '{n} تخمين',
  'distanceLabel': 'المسافة',
  'noGuessesYet': 'ابدأ بأي كلمة',
  'noGuessesBody': 'كل تخمين يُقيَّم بحسب قرب معناه من الكلمة السرية.',
  'guessHistory': 'تخميناتك',
  'hintsLeftN': '{n} متبقية',
  'hintsNone': 'لا مزيد من التلميحات',
  'noHintsYet': 'لم تكشف أي تلميح بعد',
  'showHints': 'إظهار التلميحات',
  'hideHints': 'إخفاء التلميحات',
  'submitGuess': 'إرسال التخمين',
  'gameLanguage': 'لغة اللعبة',
  'hintsRevealedN': '{n} مكشوفة',
  'systemHint': 'تلميح النظام',
  'hintAuthor': 'تلميح',
  'opponentLabel': 'الخصم',
  'sharedHistory': 'التخمينات المشتركة',
  'noRankYet': '—',
  'viewResult': 'عرض النتيجة',
  'bestRankLabel': 'أفضل مركز',
  'weeklyExpired': 'انتهى التحدي',
  'settingOn': 'مفعّل',
  'settingOff': 'متوقف',
  'errLoadInvites': 'تعذّر تحميل الدعوات — اسحب للتحديث',
  'coins': 'العملات',
  'noTranslations': 'لا توجد اقتراحات لهذه الكلمة',
  'releaseInfoSectionTitle': "بيانات اللعبة",
  'wordDataVersionLabel': "إصدار بيانات الكلمات",
  'datasetVersionLabel': "إصدار مجموعة البيانات",
  'languagePackLabel': "حزمة اللغة",
  'releaseIdLabel': "معرّف الإصدار",
  'newGamesReleaseLabel': "إصدار الألعاب الجديدة",
  'currentGameReleaseLabel': "إصدار اللعبة الحالية",
  'currentGamePinnedLabel': "مثبّت",
  'releaseChangedForNewGamesMessage':
      "تبقى لعبتك الحالية على إصدارها الأصلي، بينما تستخدم الألعاب الجديدة الإصدار الأحدث.",
  'legacyUnknownReleaseLabel': "إصدار قديم غير معروف",
  'releaseStatusActiveLabel': "نشط",
  'sourceCommitLabel': "بصمة الكود",
  'releaseComponentsLabel': "مُركَّب من",
  'sessionReleaseLabel': "إصدار هذه اللعبة",
  'releaseUpdatedLabel': "تحديث السياسة",
  'nasijBandDistant': "بعيد",
  'nasijBandAdjacent': "مجاور",
  'nasijBandRelated': "قريب",
  'nasijBandNear': "وشيك",
  'nasijBandTouching': "ملامس",
  'nasijBandSolved': "محلولة",
  'gameplayModeClassic': "كلاسيكي",
  'gameplayModeOrbit': "نسيج",
  'translationTitle': "من العربية إلى الإنجليزية",
  'translationLoading': "جارٍ البحث عن ترجمات…",
  'translationError': "تعذّر تحميل الترجمات",
  'translationRetry': "أعد المحاولة",
  'translationMore': "ترجمات أخرى",
  'translationAnnounce': "تتوفر {n} اقتراحات ترجمة",
  'closest': 'الأقرب',
  'latest': 'الأحدث',
  'hints': 'التلميحات',
  'enterYourWord': 'اكتب كلمتك...',
  'solved': 'أحسنت!',
  'viewMyRank': 'عرض ترتيبي',
  'weeklyLoadError': 'تعذّر تحميل التحدي',
  'startGame': 'ابدأ اللعب',
  'winner': 'الفائز',
  'roomsWon': 'غرف',
  'bestLabel': 'الأفضل',
  'uDayFull': 'أيام',
  'uHourFull': 'ساعة',
  'uMinFull': 'دقيقة',
  'theWordWas': 'الكلمة كانت',
  'unknownPlayer': 'لاعب مجهول',
  // ranked screen
  'chooseStake': 'اختر الرهان',
  'noTiers': 'لا توجد مستويات متاحة حالياً',
  'searchFailed': 'تعذّر بدء البحث. حاول مرة أخرى.',
  'rating': 'التقييم',
  'record': 'السجل',
  'entryPrize': 'دخول {e} · الجائزة {p}',
  'winnerTakesStake': 'الفائز يأخذ الرهان',
  'insufficientBalance': 'رصيد غير كافٍ',
  'search': 'ابحث',
  'searchingOpponent': 'نبحث عن خصم…',
  'winShort': 'ف',
  'lossShort': 'خ',
  // ranked match
  'vs': 'ضد',
  'ready': 'جاهز',
  'getReady': 'استعدّ لبدء المباراة',
  'theWordLabel': 'الكلمة',
  'timeline': 'زمني',
  'imReady': 'أنا جاهز',
  'waitingOpponent': 'بانتظار الخصم…',
  'youWon': 'فزت!',
  'matchEnded': 'انتهت المباراة',
  'ratingPts': 'تقييم',
  'yourTurn': 'دورك',
  'opponentTurn': 'دور الخصم',
  'secShort': 'ث',
  'revealHint': 'افتح تلميحاً',
  'availableToInvite': 'المتاحون للدعوة الآن',
  'shareRoomCode': 'رمز اللعبة: {code}',
};
